services:
  homebinary-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: build-homebinary-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./engine/auth:/app/engine/auth
    environment:
      - PORT=3000
      - NODE_ENV=production
